export PATH="/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/bin:/opt/apps/pixi:/u/aleksand/.pixi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
export CONDA_PREFIX="/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs"
export PIXI_PROJECT_ROOT="/u/aleksand/COMPASS"
export PIXI_PROJECT_NAME="COMPASS_UC3"
export PIXI_EXE="/opt/apps/pixi/pixi"
export PIXI_IN_SHELL="1"
export PIXI_PROJECT_MANIFEST="/u/aleksand/COMPASS/pixi.toml"
export PIXI_PROJECT_VERSION="0.1.0"
export CONDA_DEFAULT_ENV="COMPASS_UC3:compass-snake-sfincs"
export PIXI_ENVIRONMENT_NAME="compass-snake-sfincs"
export PIXI_ENVIRONMENT_PLATFORMS="linux-64,win-64"
export PIXI_PROMPT="(COMPASS_UC3:compass-snake-sfincs) "
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/gdal-activate.sh"
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/geotiff-activate.sh"
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libarrow_activate.sh"
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libglib_activate.sh"
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libxml2_activate.sh"
. "/u/aleksand/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/proj4-activate.sh"

