. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-wflow/etc/conda/deactivate.d/gdal-deactivate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-wflow/etc/conda/deactivate.d/geotiff-deactivate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-wflow/etc/conda/deactivate.d/libglib_deactivate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-wflow/etc/conda/deactivate.d/libxml2_deactivate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-wflow/etc/conda/deactivate.d/proj4-deactivate.sh"
export PATH="/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/bin:/opt/apps/pixi:/opt/apps/anaconda3/miniconda3/bin:$/u/couasnon/miniconda3/bin/python:/opt/apps/cdo/1.9.10_gcc9.2.0/bin:/u/couasnon/julia-1.10.3/bin:/u/couasnon/.pixi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
export CONDA_PREFIX="/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm"
export PIXI_EXE="/opt/apps/pixi/pixi"
export PIXI_PROJECT_ROOT="/u/couasnon/git_repos/compound-flooding-tropical-cyclones"
export PIXI_PROJECT_NAME="COMPASS_UC3"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_IN_SHELL="1"
export PIXI_PROJECT_MANIFEST="/u/couasnon/git_repos/compound-flooding-tropical-cyclones/pixi.toml"
export CONDA_DEFAULT_ENV="COMPASS_UC3:compass-snake-dfm"
export PIXI_ENVIRONMENT_NAME="compass-snake-dfm"
export PIXI_ENVIRONMENT_PLATFORMS="linux-64,win-64"
export PIXI_PROMPT="(COMPASS_UC3:compass-snake-dfm) "
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/gdal-activate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/geotiff-activate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/libarrow_activate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/libglib_activate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/libxml2_activate.sh"
. "/u/couasnon/git_repos/compound-flooding-tropical-cyclones/.pixi/envs/compass-snake-dfm/etc/conda/activate.d/proj4-activate.sh"

