export PATH="/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/bin:/opt/apps/pixi:/u/aleksand/.pixi/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
export CONDA_PREFIX="/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_IN_SHELL="1"
export PIXI_PROJECT_ROOT="/p/11210471-001-compass/02_Models/workflow_test/COMPASS"
export PIXI_EXE="/opt/apps/pixi/pixi"
export PIXI_PROJECT_MANIFEST="/p/11210471-001-compass/02_Models/workflow_test/COMPASS/pixi.toml"
export PIXI_PROJECT_NAME="COMPASS_UC3"
export CONDA_DEFAULT_ENV="COMPASS_UC3:compass-snake-sfincs"
export PIXI_ENVIRONMENT_NAME="compass-snake-sfincs"
export PIXI_ENVIRONMENT_PLATFORMS="win-64,linux-64"
export PIXI_PROMPT="(COMPASS_UC3:compass-snake-sfincs) "
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/gdal-activate.sh"
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/geotiff-activate.sh"
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libarrow_activate.sh"
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libglib_activate.sh"
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libxml2_activate.sh"
. "/p/11210471-001-compass/02_Models/workflow_test/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/proj4-activate.sh"

