# Defining parameters to run the snakemake pipeline


root_dir:    11210471-001-compass
dir_data:    01_Data
dir_models:  02_Models
dir_runs:    03_Runs
runname_ids: 
    Idai:
        tc_name: Idai
        region: sofala
        bbox_sfincs: "[34.33,-20.12,34.95,-19.30]" # format: [x1 y1 x2 y2]
        bbox_dfm: "[32.3,42.5,-27.4,-9.5]" # format: [x1 x2 y1 y2]
        start_time: 20190309 000000
        end_time: 20190325 060000
        forcing: era5_hourly
        dfm_res: '450'
        bathy: 'gebco2024_MZB'
        wind_forcing: spw_IBTrACS_CF0_Idai
        tidemodel: 'GTSMv41opendap' # tidemodel: FES2014, FES2012, EOT20, GTSMv4.1, GTSMv4.1_opendap
        dfm_obs_file: coastal_coupling_DFM_obs_points_MZB
        verification_points: 'MZB_Sofala_IHO_obs.xyn'
        config_sfincs_base: sfincs_base_build_MZB.yml
        utmzone: 36s
        
        # Change to:
        # precip_forcing: ["ERA5land_Idai","TAMSAT_Idai"]
        # wind_forcing: ["spw_IBTrACS_ext","IFS"]
        # CF_value_rain: [-7]
        CF_value_wind: [0]
        CF_value_SLR: [-0.14] # in m
    # Freddy1:
    #     tc_name: Freddy1
    #     region: quelimane #?
    #     bbox_sfincs: "[36.7,-18.35,37.41,-17.64]"
    #     dfm_output_bbox: "[34,-23.3,36,-21] "
    #     file_spw: tc_Freddy_CF0_2023036S12118_ext9d.spw
    #     start_time: 20230221 000000
    #     end_time: 20230305 060000
    #     forcing: era5_hourly
    # Freddy2:
    #     tc_name: Freddy2
    #     region: quelimane
    #     bbox: "[36.7,-18.35,37.41,-17.64]"
    #     bbox_dfm: "[36.3,-19.7,38,-16.7]"
    #     file_spw: spw_IBTrACS_ext_Freddy2_factual
    #     start_time: 20230304 000000
    #     end_time: 20230323 060000
    #     forcing: era5_hourly
    #     dfm_res: "450"
    #     bathy: "gebco2024"
    #     wind_forcing: "spw_IBTrACS_ext"
    #     dfm_obs_file: 'coastal_coupling_DFM_obs_points_MZB'
    #     verification_points: ''
    # Kenneth:
    #     tc_name: Kenneth
    #     region: 
    #     bbox: "[36.7,-18.35,37.41,-17.64]"
    #     dfm_output_bbox: "[40,-13.5,42,-11.2]"
    #     file_spw: tc_Kenneth_CF0_2019112S10053_ext9d.spw
    #     start_time: 20190421 210000
    #     end_time: 20190505 000000
    #     forcing: era5_hourly




