# Defining parameters to run the snakemake pipeline
root_dir:    11210471-001-compass # root directory of your project, it is appended to the disk drive name specified in the smk files (e.g. c:/ or  p:/)
dir_data:    01_Data              # Folder where data to build the models is saved
dir_models:  02_Models            # Folder where the base models will be saved (without dynamic forcing data)
dir_runs:    03_Runs              # Folder where model runs will be saved (with forcing)

runname_ids: 
    Idai3:   
        #Settings of the workflow                           # name of the model run
        tc_name: Idai                                # name of the storm. For tropical cyclones, this can be the name of the TC
        region: sofala                                    # name of the region will be used in naming folders 
        
        #For all model setups
        start_time: 20190309 000000                         # Start time of the SFINCS model run in format: YYYYMMDD HHMMSS           
        end_time: 20190325 060000                           # End time of the SFINCS model run in format: YYYYMMDD HHMMSS          
        forcing: era5_hourly_zarr                           # forcing dataset for the rainfall data (matching to the DataCatalog handle)
        wind_forcing: spw_IBTrACS_CF0_Idai                           # wind and pressure dataset (used for coastal surge modelling)
        bathy: gebco2024_MZB                                        # DataCatalog handle for the bathymetry dataset
        #bathy: emodnet_bathy_E4_2018_msl                   # DataCatalog handle for the bathymetry dataset

        #Models selections
        use_dfm: False                                      # use the coastal hydrodynamic model D-FM
        use_wflow: True                                     # use the hydrological model Wflow        
        
        #DFM model user-defined settings
        bbox_dfm: "[-4.1849,-2.5063, 51,51.7]"               # Bounding box for the coastal hydrodynamic model in format: [lon_min, lon_max, lat_min, lat_max]
        dfm_res: '450'                                      # coastal hydrodynamic model maximum (finest) resolution in meters (resolution at the coast)
        dfm_dxy_base: '0.2'                                # coastal hydrodynamic model base grid resolution in degrees (this is the width of the largest grid cells)        
        tidemodel: 'GTSMv41opendap'                         # tidal model for boundary conditions as can be read by dfm_tools: FES2014, FES2012, EOT20, GTSMv4.1, GTSMv4.1_opendap
        dfm_obs_file: coastal_coupling_DFM_obs_points_MZB  # DataCatalog handle for the coastal points used to couple coastal hydro model D-FM and the flood model SFINCS
        dfm_verification_points: dfm_verif_points_MZB      # DataCatalog handle for the additional points where D-FM output will be saved for validation purposes

        #SFINCS model user-defined settings
        config_sfincs_base: sfincs_base_build.yml           # name of the SFINCS configuration file (default: sfincs_base_build.yml)  ## I think this should be removed?
        bbox_sfincs: "[34.33,-20.12,34.95,-19.30]" # Bounding box for the flood model in format: [lon_min, lat_min, lon_max, lat_max]
        dfm_coastal_mask: coastal_coupling_msk_MZB         # DataCatalog handle for the coastal coupling mask
        coastal_ts: gtsm_codec_reanalysis_hourly_v2                   # DataCatalog handle for the coastal boundary conditions if D-FM is NOT used
        utmzone: 36s                                        # UTM zone (needed by SFINCS, see https://www.latlong.net/lat-long-utm.html)                                                

