# Defining parameters to run the snakemake pipeline

root_dir:    11210471-001-compass # root directory of your project, it is appended to the disk drive name specified in the smk files (e.g. c:/ or  p:/)
dir_data:    01_Data 
dir_models:  02_Models            # Folder where the base models will be saved (without dynamic forcing data)
dir_runs:    03_Runs              # Folder where model runs will be saved (with forcing)
runname_ids: 
    SomersetLevels:                                         # name of the model run
        tc_name: winterstorm                                # name of the storm. For tropical cyclones, this can be the name of the TC
        region: somerset                               # name of the region will be used in naming folders 
        bbox_sfincs: "[-3.2913,50.9637,-2.5063,51.3508]"    # Bounding box for the flood model in format: [lon_min, lat_min, lon_max, lat_max]
        bbox_dfm: "[-4.1849,-2.5063, 51,51.7]"      # Bounding box for the coastal hydrodynamic model in format: [lon_min, lon_max, lat_min, lat_max]
        start_time: 20200101 000000                                     
        end_time: 20200115 000000                                   
        forcing: era5_hourly                                # forcing dataset for the rainfall data (matching to the DataCatalog handle)
        wind_forcing: era5_hourly                           # wind and pressure dataset (used for coastal surge modelling)
        #bathy: emodnet_bathy_E4_2018_msl                   # DataCatalog handle for the bathymetry dataset
        bathy: gebco                                        # DataCatalog handle for the bathymetry dataset
        use_dfm: False                                      # use the coastal hydrodynamic model D-FM
        coastal_ts: gtsm_codec_reanalysis_hourly_v1         # DataCatalog handle for the coastal boundary conditions if D-FM is NOT used
        dfm_res: '100'                                      # coastal hydrodynamic model maximum (finest) resolution in meters (resolution at the coast)
        dfm_dxy_base: '0.05'                                # coastal hydrodynamic model base grid resolution in degrees (this is the width of the largest grid cells)        
        tidemodel: 'GTSMv41opendap'                         # tidal model for boundary conditions as can be read by dfm_tools: FES2014, FES2012, EOT20, GTSMv4.1, GTSMv4.1_opendap
        dfm_obs_file: coastal_coupling_DFM_obs_points_SMST  # DataCatalog handle for the coastal points used to couple coastal hydro model D-FM and the flood model SFINCS
        dfm_coastal_mask: coastal_coupling_msk_SMST         # DataCatalog handle for the coastal coupling mask
        dfm_verification_points: dfm_verif_points_SMST      # DataCatalog handle for the additional points where D-FM output will be saved for validation purposes
        config_sfincs_base: sfincs_base_build.yml           # name of the SFINCS configuration file (default: sfincs_base_build.yml)
        utmzone: 30u                                        # UTM zone (needed by SFINCS, see https://www.latlong.net/lat-long-utm.html)                                                
