# Defining parameters to run the snakemake pipeline



dir_runs:    ../computations
dir_spw:     /p/11210471-001-compass/02_Models/Delft3DFM/mozambique_model/boundary_conditions/meteo/TC/
datacatalog: ../datacatalog_general.yml
runname_ids: 
    Idai:
        tc_name: Idai
        bbox: "[34.33,-20.12,34.95,-19.30]"
        file_spw: tc_IDAI_2019063S18038_ext9d.spw 
    Freddy2:
        tc_name: Freddy2
        bbox: "[36.7,-18.35,37.41,-17.64]"
        file_spw: tc_FREDDY_2023061S22036_ext9d.spw



