# Defining parameters to run the snakemake pipeline


root_dir:    11210471-001-compass
dir_runs:    ../03_Runs
dir_spw:     02_Models/Delft3DFM/mozambique_model/boundary_conditions/meteo/TC/
datacatalog: data_catalogs/datacatalog_general.yml
runname_ids: 
    # Idai:
        # tc_name: Idai
        # region: sofala
        # bbox: "[34.33,-20.12,34.95,-19.30]"
        # file_spw: tc_IDAI_2019063S18038_ext9d.spw 
        # start_time: 20190309 000000
        # end_time: 20190325 060000
        # forcing: era5_hourly
    Freddy2:
        tc_name: Freddy2
        region: quelimane
        bbox: "[36.7,-18.35,37.41,-17.64]"
        file_spw: tc_FREDDY_2023061S22036_ext9d.spw
        start_time: 20230304 000000
        end_time: 20230323 060000
        forcing: era5_hourly



