# Defining parameters to run the snakemake pipeline


root_dir:    11210471-001-compass
dir_runs:    ../03_Runs
dir_spw:     02_Models/Delft3DFM/mozambique_model/boundary_conditions/meteo/TC/
datacatalog: data_catalogs/datacatalog_general.yml
runname_ids: 
    Idai:
        tc_name: Idai
        region: sofala
        bbox: "[34.33,-20.12,34.95,-19.30]"
        file_spw: tc_IDAI_2019063S18038_ext9d.spw 
        start_time: 20190309 000000
        end_time: 20190325 060000
        forcing: era5_hourly
        dfm_res: "450"
        bathy: "gebco2024"
        tidemodel: 'GTSMv4.1_opendap' # tidemodel: FES2014, FES2012, EOT20, GTSMv4.1, GTSMv4.1_opendap

        dfm_output_bbox:"[34, -20.5, 35.6, -19.5]" # same as bbox?
        dfm_obs_file: 'p:/11210471-001-compass/01_Data/Coastal_boundary/points/coastal_bnd_MZB_5mMSL_points_1km.shp'
        verification_points: 'p:/11210471-001-compass/02_Models/Delft3DFM/mozambique_model/geometry/output_locations/MZB_Sofala_IHO_obs.xyn'

bbox_dfm: "[32.3,42.5,-27.4,-9.5]"

        # Change to:
        # precip_forcing: ["ERA5land_Idai","TAMSAT_Idai"]
        # CF_value_rain: [-7]
        # wind_forcing: ["spw_IBTrACS_ext","IFS"]
        # CF_value_wind: [-10, -12]
        # CF_value_SLR: [14]
    # Freddy2:
    #     tc_name: Freddy2
    #     region: quelimane
    #     bbox: "[36.7,-18.35,37.41,-17.64]"
    #     file_spw: tc_FREDDY_2023061S22036_ext9d.spw
    #     start_time: 20230304 000000
    #     end_time: 20230323 060000
    #     forcing: era5_hourly




