root_dir: 11210471-001-compass

# Defining start and end date
start_date: 2019-03-09
end_date: 2019-03-24

bbox: "[34.33,-20.12,34.95,-19.30]"

# Defining the rainfall datasets
precip_name: ["ERA5land_Idai","TAMSAT_Idai"]
CF_value_rain: [-7]

# Defining the wind datasets
# wind_name: ["ERA5_spw"]
# CF_value_rain: [-10]
