. "/opt/apps/anaconda3/miniconda3/etc/conda/deactivate.d/libxml2_deactivate.sh"
export PATH="/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/bin:/opt/apps/pixi:/u/couasnon/.pixi/bin:/opt/apps/anaconda3/miniconda3/condabin:$/u/couasnon/miniconda3/bin/python:/opt/apps/cdo/1.9.10_gcc9.2.0/bin:/u/couasnon/julia-1.10.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin"
export CONDA_PREFIX="/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs"
export PIXI_EXE="/opt/apps/pixi/pixi"
export PIXI_PROJECT_MANIFEST="/u/couasnon/git_repos/COMPASS/COMPASS/pixi.toml"
export PIXI_IN_SHELL="1"
export PIXI_PROJECT_ROOT="/u/couasnon/git_repos/COMPASS/COMPASS"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_PROJECT_NAME="COMPASS_UC3"
export CONDA_DEFAULT_ENV="COMPASS_UC3:compass-snake-sfincs"
export PIXI_ENVIRONMENT_NAME="compass-snake-sfincs"
export PIXI_ENVIRONMENT_PLATFORMS="win-64,linux-64"
export PIXI_PROMPT="(COMPASS_UC3:compass-snake-sfincs) "
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/gdal-activate.sh"
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/geotiff-activate.sh"
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libarrow_activate.sh"
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libglib_activate.sh"
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/libxml2_activate.sh"
. "/u/couasnon/git_repos/COMPASS/COMPASS/.pixi/envs/compass-snake-sfincs/etc/conda/activate.d/proj4-activate.sh"

